### PR TITLE
Add QBWC.delete_job

### PR DESCRIPTION
**Pull request by rchekaluk**
Allow a job to delete itself after completion (as discussed [here](https://github.com/skryl/qbwc#creating-jobs)). This introduces a new required parameter for handle_response in order to access the current job:

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
This seems to have stuff from #40 too.

**Comment by rchekaluk** [comment]
Only because it's a branch of a branch. I believe that once https://github.com/skryl/qbwc/pull/40 is merged, it's items will disappear from here.

**Comment by JasonBarnabe** [comment]
Can you make `delete_job` able to handle a `Job` parameter too? e.g. `job = job.name if job.is_a?(Job)`.

This has failing tests due to the fake requests, just like #40.

**Comment by rchekaluk** [comment]
Done, ready for re-review.

**Pull request merged**
