### PR TITLE
Allow suppressing sensitive log lines

### PR DESCRIPTION
**Pull request by rchekaluk**
Adds new config parameter log_sensitive_lines (default `false` on production, and `true` otherwise) that determines if request and response content is logged.

Emits a log entry at each send_request operation that doesn't contain sensitive information (requires minor code restructuring).

Standardizes the format (string qbXML or hash) of logged requests and responses in this way:
* Internal requests: logged in the format in which they were provided (either string or hash)
* Requests sent to QuickBooks: logged as string qbXML
* Responses from QuickBooks: logged as string qbXML (this required a minor change)

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
`log_sensitive_lines` would make me ask "what lines are sensitive?". What about simply `log_requests_and_responses`?

**Comment by rchekaluk** [comment]
Done.

**Comment by JasonBarnabe** [comment]
```
NoMethodError (undefined method `name' for nil:NilClass):
  /www/qbwc/lib/qbwc/session.rb:67:in `request_to_send'
  /www/qbwc/lib/qbwc/controller.rb:130:in `send_request'
```

**Comment by rchekaluk** [comment]
Fixed.

**Pull request merged**
